print ("Hola soy Estefania")
print ("Primer cambio")
print ("Hola soy David")
print ("PRIMERA MEZCLA DAVID")
print("Primera Mezcla Estefania")
print ("Es una mezcla")
print("Primera mezcla Reyes")
print("Esperemos esto se solucione")
suma=3+2
print (suma)